/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Logica.ListaSdoble;
import Logica.Nodo;

/**
 *
 * @author osboxes
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    
    private ListaSdoble palabras;
    private HelpScreen ayuda;
    public ventana() {
        ayuda= new HelpScreen();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchInput = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OPMenu = new javax.swing.JMenu();
        OPHelp = new javax.swing.JMenu();
        OPOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spider search");
        setMinimumSize(new java.awt.Dimension(950, 680));
        getContentPane().setLayout(null);

        SearchInput.setToolTipText("Ingrese el lo que desee buscar");
        getContentPane().add(SearchInput);
        SearchInput.setBounds(210, 50, 450, 35);

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(700, 50, 74, 37);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Proyecto programado 1\nSpider search stage 1\nDesarrollado por Ellioth Ramirez /2014057732\nInstituto Tecnologico de Costa Rica\nCE-1103\nSem1-2015");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 150, 810, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/osboxes/NetBeansProjects/SpiderBot/SpriderBot/iconoP1.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 150, 120);

        OPMenu.setText("Options");

        OPHelp.setText("Ayuda");
        OPHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPHelpActionPerformed(evt);
            }
        });
        OPMenu.add(OPHelp);

        OPOut.setText("Salir");
        OPOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPOutActionPerformed(evt);
            }
        });
        OPMenu.add(OPOut);

        jMenuBar1.add(OPMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPOutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OPOutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void OPHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPHelpActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ayuda.setVisible(true);
    }//GEN-LAST:event_OPHelpActionPerformed

    
    public void getText(){
        String cadena=SearchInput.getText();
        String contenedor="";
        Nodo tmp;
        int x=0;
        int y=x+1;
        while(y<cadena.length()){
            if(cadena.substring(x, y).equals(" ")){
                tmp= new Nodo(contenedor);
                palabras.enQueue(tmp);
            }
            else
                contenedor.concat(cadena.substring(x,y));
            x=y;
            y++;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu OPHelp;
    private javax.swing.JMenu OPMenu;
    private javax.swing.JMenu OPOut;
    private javax.swing.JTextField SearchInput;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
